BaseURL = "https://shinya-sato.com/"
defaultContentLanguage = "ja"
title = "サトウシンヤのポートフォリオ"
Publishdir = 'docs'
Paginate = 12
googleAnalytics = "UA-120088829-1"

relativeURLs = true
canonifyURLs = true

[params]
  github = "https://github.com/cookboys"

[Languages]
[Languages.ja]
  weight = 1
  domain = "shinya-sato.com/"
  homeTitle = "ようこそ、サトウシンヤのポートフォリオサイトへ"
  siteName = "サトウシンヤのポートフォリオサイト"
  languageName = "日本語"
  languageCode = "ja-JP"
  keyword = "サトウシンヤ, ポートフォリオ, ウェブデザイン, ウェブデザイナー, 静的サイトジェネレーター"
  description = "初めまして、1987年生まれのデザイナーのサトウシンヤです。デザイン、コーディング、静的サイトジェネレーターを使ったサイト制作が得意です。"

[Languages.en]
  weight = 2
  domain = "shinya-sato.com/en/"
  homeTitle = "Welcome to Shinya Sato portfolio site"
  siteName = "portfolio site of Shinya Sato"
  languageName = "English"
  languageCode = "en-US"
  keyword = "Shinya Sato, Portfolio, Web Design, Web Designer, Static Site Generator"
  description = "Nice to meet you, my name is Shinya Sato, a designer born in 1987. I am good at designing, coding, and creating sites using static site generators."

[Languages.cn]
  weight = 3
  domain = "shinya-sato.com/cn/"
  homeTitle = "欢迎来到サトウシンヤ的投资组合网站"
  siteName = "サトウシンヤ的投资组合网站"
  languageName = "中文(简体)"
  languageCode = "zh-CN"
  keyword = "サトウシンヤ, 投资组合，网页设计，网页设计师，静态网站生成器"
  description = "很高兴见到你，我的名字是サトウシンヤ，1987年出生的设计师。 我擅长使用静态站点生成器进行设计，编码和创建站点。"

[[menu.languages]]
  name = "日本語"
  weight = 1
  url = "/"

[[menu.languages]]
  name = "English"
  weight = 2
  url = "/en/"

[[menu.languages]]
  name = "中文(简体)"
  weight = 3
  url = "/cn/"

[taxonomies]
tag = "tags"
category = "categories"
