BaseURL = "https://shinya-sato.com/"
defaultContentLanguage = "ja"
title = "サトウシンヤのポートフォリオサイト"
Publishdir = 'docs'
Paginate = 12
googleAnalytics = "UA-120088829-1"

relativeURLs = true
canonifyURLs = true

[params]
  image_symbol = "/images/symbol.svg"
  icon_ai = "/images/icon/icon_ai.svg"
  icon_psd = "/images/icon/icon_psd.svg"
  icon_xd = "/images/icon/icon_xd.svg"
  icon_an = "/images/icon/icon_an.svg"
  icon_vim = "/images/icon/icon_vim.svg"
  icon_hyper = "/images/icon/icon_hyper.svg"
  icon_netlify = "/images/icon/icon_netlify.svg"
  icon_html5 = "/images/icon/icon_html5.svg"
  icon_css = "/images/icon/icon_css.svg"
  icon_sass = "/images/icon/icon_sass.svg"
  icon_postcss = "/images/icon/icon_postcss.svg"
  icon_rails = "/images/icon/icon_rails.svg"
  icon_git = "/images/icon/icon_git.svg"
  icon_jekyll = "/images/icon/icon_jekyll.svg"
  icon_hugo = "/images/icon/icon_hugo.svg"
  icon_vuepress = "/images/icon/icon_vuepress.svg"
  icon_wordpress = "/images/icon/icon_wordpress.svg"
  repo_portfolio = "https://github.com/cookboys/portfolio.github.io"
  placeholder = "/images/placeholder.png"
  placeholder_photos = "/images/placeholder_photos.png"

[Languages]
[Languages.ja]
  weight = 1
  domain = "shinya-sato.com/"
  homeTitle = "ようこそ、サトウシンヤのポートフォリオサイトへ"
  siteName = "サトウシンヤのポートフォリオサイト"
  languageName = "日本語"
  languageCode = "ja-JP"
  keyword = "サトウシンヤ, ポートフォリオ, ウェブデザイン, ウェブデザイナー, 静的サイトジェネレーター"
  description = "初めまして、1987年生まれのデザイナーのサトウシンヤです。デザイン、コーディング、静的サイトジェネレーターを使ったサイト制作が得意です。"

[Languages.en]
  weight = 2
  domain = "shinya-sato.com/en/"
  homeTitle = "Welcome to Shinya Sato portfolio site"
  siteName = "portfolio site of Shinya Sato"
  languageName = "English"
  languageCode = "en-US"
  keyword = "Shinya Sato, Portfolio, Web Design, Web Designer, Static Site Generator"
  description = "Nice to meet you, my name is Shinya Sato, a designer born in 1987. I am good at designing, coding, and creating sites using static site generators."

[Languages.cn]
  weight = 3
  domain = "shinya-sato.com/cn/"
  homeTitle = "欢迎来到サトウシンヤ的投资组合网站"
  siteName = "サトウシンヤ的投资组合网站"
  languageName = "中文(简体)"
  languageCode = "zh-CN"
  keyword = "サトウシンヤ, 投资组合，网页设计，网页设计师，静态网站生成器"
  description = "很高兴见到你，我的名字是サトウシンヤ，1987年出生的设计师。 我擅长使用静态站点生成器进行设计，编码和创建站点。"

[[menu.languages]]
  name = "日本語"
  weight = 1
  url = "/"

[[menu.languages]]
  name = "English"
  weight = 2
  url = "/en/"

[[menu.languages]]
  name = "中文(简体)"
  weight = 3
  url = "/cn/"

[taxonomies]
tag = "tags"
category = "categories"
